[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
    framework = "vite"
    targetPort = 5173
    port = 8888
    functions = "netlify/functions"
